// Generated by gencpp from file rc_car/Lidar.msg
// DO NOT EDIT!


#ifndef RC_CAR_MESSAGE_LIDAR_H
#define RC_CAR_MESSAGE_LIDAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rc_car
{
template <class ContainerAllocator>
struct Lidar_
{
  typedef Lidar_<ContainerAllocator> Type;

  Lidar_()
    : angle(0)
    , dist(0.0)
    , obstacle_flag(0)  {
    }
  Lidar_(const ContainerAllocator& _alloc)
    : angle(0)
    , dist(0.0)
    , obstacle_flag(0)  {
  (void)_alloc;
    }



   typedef uint32_t _angle_type;
  _angle_type angle;

   typedef float _dist_type;
  _dist_type dist;

   typedef uint32_t _obstacle_flag_type;
  _obstacle_flag_type obstacle_flag;




  typedef boost::shared_ptr< ::rc_car::Lidar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_car::Lidar_<ContainerAllocator> const> ConstPtr;

}; // struct Lidar_

typedef ::rc_car::Lidar_<std::allocator<void> > Lidar;

typedef boost::shared_ptr< ::rc_car::Lidar > LidarPtr;
typedef boost::shared_ptr< ::rc_car::Lidar const> LidarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_car::Lidar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_car::Lidar_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rc_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'rc_car': ['/home/andyklam/catkin_ws/src/rc_car/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::Lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::Lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::Lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::Lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::Lidar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::Lidar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_car::Lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc9ec0058467f04029014e27cd00d521";
  }

  static const char* value(const ::rc_car::Lidar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc9ec0058467f040ULL;
  static const uint64_t static_value2 = 0x29014e27cd00d521ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_car::Lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_car/Lidar";
  }

  static const char* value(const ::rc_car::Lidar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_car::Lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 angle\n\
float32 dist\n\
uint32 obstacle_flag \n\
";
  }

  static const char* value(const ::rc_car::Lidar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_car::Lidar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.dist);
      stream.next(m.obstacle_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lidar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_car::Lidar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_car::Lidar_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.angle);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "obstacle_flag: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.obstacle_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_CAR_MESSAGE_LIDAR_H
