// Generated by gencpp from file rc_car/pid_input.msg
// DO NOT EDIT!


#ifndef RC_CAR_MESSAGE_PID_INPUT_H
#define RC_CAR_MESSAGE_PID_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rc_car
{
template <class ContainerAllocator>
struct pid_input_
{
  typedef pid_input_<ContainerAllocator> Type;

  pid_input_()
    : vel(0.0)
    , error(0.0)
    , obstacle_flag(false)  {
    }
  pid_input_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , error(0.0)
    , obstacle_flag(false)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _error_type;
  _error_type error;

   typedef uint8_t _obstacle_flag_type;
  _obstacle_flag_type obstacle_flag;




  typedef boost::shared_ptr< ::rc_car::pid_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_car::pid_input_<ContainerAllocator> const> ConstPtr;

}; // struct pid_input_

typedef ::rc_car::pid_input_<std::allocator<void> > pid_input;

typedef boost::shared_ptr< ::rc_car::pid_input > pid_inputPtr;
typedef boost::shared_ptr< ::rc_car::pid_input const> pid_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_car::pid_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_car::pid_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rc_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'rc_car': ['/home/andyklam/catkin_ws/src/rc_car/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_car::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::pid_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car::pid_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_car::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2455c9230edc930265906132ca470811";
  }

  static const char* value(const ::rc_car::pid_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2455c9230edc9302ULL;
  static const uint64_t static_value2 = 0x65906132ca470811ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_car::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_car/pid_input";
  }

  static const char* value(const ::rc_car::pid_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_car::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n\
float32 error\n\
bool obstacle_flag\n\
";
  }

  static const char* value(const ::rc_car::pid_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_car::pid_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.error);
      stream.next(m.obstacle_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_car::pid_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_car::pid_input_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "error: ";
    Printer<float>::stream(s, indent + "  ", v.error);
    s << indent << "obstacle_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_CAR_MESSAGE_PID_INPUT_H
