# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rc_car/pid_input.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pid_input(genpy.Message):
  _md5sum = "84623ee5a6b9076f2f5764e660ccbc8b"
  _type = "rc_car/pid_input"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 vel
float32 error
bool frontBlocked
bool leftBlocked
bool rightBlocked"""
  __slots__ = ['vel','error','frontBlocked','leftBlocked','rightBlocked']
  _slot_types = ['float32','float32','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vel,error,frontBlocked,leftBlocked,rightBlocked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pid_input, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vel is None:
        self.vel = 0.
      if self.error is None:
        self.error = 0.
      if self.frontBlocked is None:
        self.frontBlocked = False
      if self.leftBlocked is None:
        self.leftBlocked = False
      if self.rightBlocked is None:
        self.rightBlocked = False
    else:
      self.vel = 0.
      self.error = 0.
      self.frontBlocked = False
      self.leftBlocked = False
      self.rightBlocked = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2f3B.pack(_x.vel, _x.error, _x.frontBlocked, _x.leftBlocked, _x.rightBlocked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.vel, _x.error, _x.frontBlocked, _x.leftBlocked, _x.rightBlocked,) = _struct_2f3B.unpack(str[start:end])
      self.frontBlocked = bool(self.frontBlocked)
      self.leftBlocked = bool(self.leftBlocked)
      self.rightBlocked = bool(self.rightBlocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2f3B.pack(_x.vel, _x.error, _x.frontBlocked, _x.leftBlocked, _x.rightBlocked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.vel, _x.error, _x.frontBlocked, _x.leftBlocked, _x.rightBlocked,) = _struct_2f3B.unpack(str[start:end])
      self.frontBlocked = bool(self.frontBlocked)
      self.leftBlocked = bool(self.leftBlocked)
      self.rightBlocked = bool(self.rightBlocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2f3B = struct.Struct("<2f3B")
